name: CI - Build & Test

on:
  push:
    branches: [ "main" ]

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t devops-ci-app .

      - name: Run container
        run: |
          docker run -d --name app -p 5000:5000 devops-ci-app
          sleep 2

      - name: Smoke test HTTP response
        run: |
          curl -f http://localhost:5000 | grep "Hello from DevOps CI/CD project!"

      - name: Cleanup
        if: always()
        run: docker rm -f app

